"""fix- Importing models user and todos

Revision ID: 6196e1036eee
Revises: 
Create Date: 2025-07-29 21:00:39.712916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6196e1036eee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_todos_owner_id'), 'todos', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_index(op.f('ix_todos_owner_id'), table_name='todos')
    op.drop_column('todos', 'owner_id')
    # ### end Alembic commands ###
