"""feat- Created column phone_number for user

Revision ID: 6fdc25edd1a0
Revises: ab119a3c862f
Create Date: 2025-08-18 21:55:55.516150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdc25edd1a0'
down_revision: Union[str, Sequence[str], None] = 'ab119a3c862f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_todos_owner_id_users",  # nome da constraint
            "users",                    # tabela referenciada
            ["owner_id"],               # coluna local
            ["id"]                      # coluna remota
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_constraint("fk_todos_owner_id_users", type_='foreignkey')

    # ### end Alembic commands ###
